# Generated by Django 4.2.3 on 2023-08-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='update_at',
            field=models.DateField(null=True, verbose_name='Дата изменения'),
        ),
    ]
